# Initialization File

# This file contains the minimal settings for liblouisutdml operation. 
# You can change them for your installation. Settings needed for a 
# particular language or braille code should be in an appropriately 
# named configuration file. See preferences.cfg for an example.

# This file is read automatically when liblouisutdml starts. You should 
# use it as a reference but never specify it as a configuration file.

# Notes
# To get UTDML specify formatFor utd

cellsPerLine 40
linesPerPage 25
interpoint no
lineEnd \r\n
pageEnd \f
fileEnd ^z
printPages yes
braillePages yes
numberBraillePages yes
paragraphs yes
beginningPageNumber 1
printPageNumberAt top
braillePageNumberAt bottom
hyphenate no
outputEncoding ascii8
inputTextEncoding ascii8
backFormat plain
backLineLength 70
formatFor textDevice
lineFill '
literarytextTable en-us-g2.ctb
uncontractedTable en-us-g1.ctb
compbrlTable en-us-comp8.ctb
mathtextTable en-us-g2.ctb
mathexprTable nemeth.ctb
editTable nemeth_edit.ctb
#semanticFiles *,nemeth.sem
xmlheader "<?xml version='1.0' encoding='UTF-8' standalone='yes'?>"
internetAccess no
newEntries yes

style para
	firstLineIndent 2
style heading1
	firstLineIndent 2
style heading2
	firstLineIndent 2
style heading3
	firstLineIndent 2
style heading4
	firstLineIndent 2

