
#ifndef BLUEZQT_VERSION_H
#define BLUEZQT_VERSION_H

#define BLUEZQT_VERSION_STRING "5.18.0"
#define BLUEZQT_VERSION_MAJOR 5
#define BLUEZQT_VERSION_MINOR 18
#define BLUEZQT_VERSION_PATCH 0
#define BLUEZQT_VERSION ((5<<16)|(18<<8)|(0))

#endif
