
#ifndef KWAYLAND_VERSION_H
#define KWAYLAND_VERSION_H

#define KWAYLAND_VERSION_STRING "5.5.5"
#define KWAYLAND_VERSION_MAJOR 5
#define KWAYLAND_VERSION_MINOR 5
#define KWAYLAND_VERSION_PATCH 5
#define KWAYLAND_VERSION ((5<<16)|(5<<8)|(5))

#endif
